ChrisKujawa/zdb

zdb/src/main/java/io/zeebe/zdb/LogCommand.java, zdb/src/main/java/io/zeebe/zdb/LogPrintCommand.java, zdb/src/main/java/io/zeebe/zdb/ZeebeDebugger.java, zdb/src/main/java/io/zeebe/zdb/impl/log/CompactRecordLogger.java, zdb/src/main/java/io/zeebe/zdb/impl/log/LogPrint.java
This PR adds the CompactRecordLogger from zeebe-test-util. 
To make it compatible with the current zdb version, it had to be copied and changed to fit the 0.26 record value types. It also makes some changes on how the records are read, since the CompactRecordLogger requires an in-memory collection of all records it prints.
This PR adds the --format (or -f) option to `log print`, it's default is json
```
$ zdb log print
Missing required option: '--path=LOG_PATH'
Usage: zdb log print [-f=[json, compact]] -p=LOG_PATH
Print's the complete log to standard out
-f, --format=[json, compact]
The output format
Default: json
-p, --path=LOG_PATH   The path to the partition log data, should end with the
partition id.
```
It also has an option for `compact`. Choosing this results in a compacted output: …
=> Compact log for 0.26 and lower

README.md
ReadMe still referenced the workflow command, which has been renamed to process
=> Fixed readme by change workflows to processes

backend/src/main/kotlin/io/zell/zdb/log/LogContent.kt, backend/src/test/kotlin/ZeebeLogTest.java
The data of records in a single batch was not displayed correctly. All records had same position for example. The other metadata were also wrong.
=> fix: donot reuse the objects for reading multiple records in batch

backend/pom.xml
It seems some dependencies are needed during runtime, bring most of them back to be safe
=> deps: bring deps back

backend/src/main/kotlin/io/zell/zdb/state/incident/IncidentDetails.kt, backend/src/main/kotlin/io/zell/zdb/state/incident/IncidentState.kt, backend/src/test/kotlin/ZeebeStateTest.java
The key of an incident is important information, especially for the list
command. Consider having some incident in the state which you're looking
up with zdb:
zdb incident -p ./data/raft-partition/partitions/1/1runtime list | jq
Which then shows you all kinds of details about incidents, except the
key. However, the key is necessary to resolve the issue. So often you're
actually looking for that data.
Adding it is realatively easy, because in both the list and entity
command we already have the incident key available when we create the
details object.
=> add key to incident details

cli/zdb, zdb
Hi,
thanks very much for this tool.
In our pipeline, I do bake it into the Zeebe broker images and realized,
when called from some folder via PATH env variable, an error occurs:
```
Error: Unable to access jarfile zdb.jar
``` 
This is a little fix, which assumes, ```zdb``` shell script and the ```zdb.jar``` file are next to each other.
Tested manually and works fine.
=> feat(cli): detect current path and make 'zdb' able to be run from any folder via PATH env var

backend/src/main/kotlin/io/zell/zdb/log/LogContent.kt, backend/src/test/kotlin/ZeebeLogTest.java, cli/src/main/java/io/zell/zdb/LogPrintCommand.java
Add support for dot file format on the log print command
```
zdb log print [-d,--dot] -p
```
Resources:
* https://graphviz.org/docs/layouts/dot/
* https://graphviz.org/doc/info/command.html
**Example:**
From test generated:
<details>
<summary>test.dot</summary>
<pre>
digraph log {
rankdir="RL";
1 [label="\nCOMMAND\nDEPLOYMENT\nCREATE\nKey: -1"];
2 [label="\nEVENT\nPROCESS\nCREATED\nKey: 2251799813685249"];
2 -> 1;
3 [label="\nEVENT\nPROCESS\nCREATED\nKey: 2251799813685250"];
3 -> 1;
4 [label="\nEVENT\nDEPLOYMENT\nCREATED\nKey: 2251799813685251"];
4 -> 1;
5 [label="\nEVENT\nDEPLOYMENT\nFULLY_DISTRIBUTED\nKey: 2251799813685251"];
5 -> 1;
6 [label="\nCOMMAND\nPROCESS_INSTANCE_CREATION\nCREATE\nKey: -1"];
7 [label="\nEVENT\nVARIABLE\nCREATED\nKey: 2251799813685253"];
7 -> 6;
8 …
=> Generate dot file format

backend/src/main/kotlin/io/zell/zdb/log/LogContent.kt, backend/src/main/kotlin/io/zell/zdb/log/LogHelper.kt, backend/src/main/kotlin/io/zell/zdb/log/LogSearch.kt, backend/src/test/kotlin/LogHelperTest.java
If a value type is read, which is unknow we will return the TypedEvent without record value which allows us to still print the record itself (toJson handle this gracefully for us).
I added only one new unit test to handle the unknown value type situation, since it is more complex to have a full functionally logged event, and this is already tested implicit via the other integration tests.
related to https://github.com/Zelldon/zdb/issues/160
=> Handle missing value types gracefully

backend/src/main/kotlin/io/zell/zdb/db/readonly/transaction/ReadonlyTransactionDb.kt, backend/src/main/kotlin/io/zell/zdb/db/readonly/transaction/ZeebeTransactionDb.java, backend/src/main/kotlin/io/zell/zdb/state/Experimental.kt, backend/src/test/kotlin/ZeebeStateTest.java, cli/src/main/java/io/zell/zdb/StateCommand.java, cli/src/main/java/io/zell/zdb/StatusCommand.java, cli/src/main/java/io/zell/zdb/ZeebeDebugger.java
To not always fix zdb on new Zeebe version, since state classes have changed etc. I would like to implemented the state view in a more generic way. 
This is my first attempt, can be seen as alpha version. It allows to iterate over the complete state, you can use it to print statistics like:
```
$ time java -jar cli/target/cli-1.6.0-SNAPSHOT-jar-with-dependencies.jar status -p /home/cqjawa/incident/2023-01-03/1/snapshots/801194-2-3258598-3298276 details | jq
{
"DEFAULT": 1,
"KEY": 1,
"PROCESS_VERSION": 1,
"PROCESS_CACHE": 5,
"PROCESS_CACHE_BY_ID_AND_VERSION": 5,
"PROCESS_CACHE_DIGEST_BY_ID": 1,
"ELEMENT_INSTANCE_PARENT_CHILD": 73333,
"ELEMENT_INSTANCE_KEY": 73333,
"NUMBER_OF_TAKEN_SEQUENCE_FLOWS": 2,
"ELEMENT_INSTANCE_CHILD_PARENT": 73333,
"VARIABLES": 4,
"JOBS": 70456,
"JOB_STATES": …
```
=> Investigate state more generically

backend/src/main/kotlin/io/zell/zdb/state/Experimental.kt, backend/src/test/kotlin/ZeebeStateTest.java, cli/pom.xml, cli/src/main/java/io/zell/zdb/StateCommand.java, pom.xml
Print the complete key-value pairs as valid json, together in a data object. The key will be printed in a hex format, in order to visualize the key correctly. Later we can add search for it.
Example
```
....
{
"cf": "INCIDENTS",
"key": "00 00 00 00 00 00 00 22 00 08 00 00 00 00 87 c4",
"value": {
"incidentRecord": {
"errorType": "EXTRACT_VALUE_ERROR",
"errorMessage": "failed to evaluate expression 'read': no variable found for name 'read'",
"bpmnProcessId": "Process_372fbfc7-9a4a-4f0b-aee5-bd96ed3e3e5d",
"processDefinitionKey": 2251799813686656,
"processInstanceKey": 2251799813686738,
"elementId": "Gateway_0ad4338",
"elementInstanceKey": 2251799813719626,
"jobKey": -1,
"variableScopeKey": 2251799813719626
}
}
},
{
"cf": "INCIDENTS",
"key": "00 00 00 00 00 00 00 22 00 08 00 00 00 00 87 …
```
=> feat: print valid json

backend/pom.xml, backend/src/main/kotlin/io/zell/zdb/db/readonly/transaction/ReadonlyTransactionDb.kt, backend/src/main/kotlin/io/zell/zdb/db/readonly/transaction/TransactionalColumnFamily.java, backend/src/main/kotlin/io/zell/zdb/log/ApplicationRecord.kt, backend/src/main/kotlin/io/zell/zdb/log/LogContent.kt, backend/src/main/kotlin/io/zell/zdb/log/LogFactory.kt, backend/src/main/kotlin/io/zell/zdb/log/LogHelper.kt, backend/src/main/kotlin/io/zell/zdb/log/LogSearch.kt, backend/src/main/kotlin/io/zell/zdb/log/NoopMetaStore.kt, backend/src/main/kotlin/io/zell/zdb/state/Experimental.kt, backend/src/main/kotlin/io/zell/zdb/state/blacklist/BlacklistState.kt, backend/src/main/kotlin/io/zell/zdb/state/general/GeneralState.kt, backend/src/main/kotlin/io/zell/zdb/state/incident/IncidentState.kt, backend/src/main/kotlin/io/zell/zdb/state/instance/InstanceState.kt, backend/src/main/kotlin/io/zell/zdb/state/process/ProcessState.kt, backend/src/test/kotlin/LogHelperTest.java, backend/src/test/kotlin/ZeebeBlacklistStateTest.java, backend/src/test/kotlin/ZeebeLogTest.java, backend/src/test/kotlin/ZeebeStateTest.java, backend/src/test/kotlin/ZeebeTest.java, cli/src/main/java/io/zell/zdb/StateCommand.java
This should make zdb compatible with  8.2.0:
1. Various moves and renames of Zeebe internal classes
2. Enabling of RocksDB WAL in various tests. Otherwise, the rocksdb instance opened in tests doesn't see all writes. This was new to me. Maybe this impacts not just tests since you can point zdb to a runtime dir where the same could happen?
3. Updates expected log indices. I didn't check in detail but probably changed because of batch processing?
4. Updates expected state keys. I think this changed because of the stream platform & engine split?
5. Provides a No-Op implementation of `MetaStore` which I think is not used by zdb.
=> Upgrade Zeebe to 8.2.0

backend/src/main/kotlin/io/zell/zdb/log/ApplicationRecord.kt, backend/src/main/kotlin/io/zell/zdb/log/LogContent.kt, backend/src/main/kotlin/io/zell/zdb/log/LogContentReader.kt, backend/src/main/kotlin/io/zell/zdb/log/LogSearch.kt, backend/src/test/kotlin/ZeebeLogTest.java, cli/src/main/java/io/zell/zdb/LogPrintCommand.java
Reads and prints the Zeebe log incremental, instead of accumulating the whole log in the CLI state. This avoids OOM on huge logs.
closes https://github.com/Zelldon/zdb/issues/120
=> Support incremental read of log

cli/src/main/java/io/zell/zdb/LogPrintCommand.java
Add new filter to the `log print` command which allows to print only an extract of the log.
For example you can skip the log until a certain position with `--fromPosition` and can limit the print until a certain position with `--toPosition`
=> Filter log for position

cli/src/main/java/io/zell/zdb/LogPrintCommand.java
Filters the log for a certain process instance, means it only prints records with the given process instance key.
The process instance key can be specified by `--instanceKey`
=> Filter log for process instance

cli/src/main/java/io/zell/zdb/StateCommand.java
The path option was not inherited which means it was not usable on the list subcommand.
closes https://github.com/Zelldon/zdb/issues/251
=> Fix path position in state list subcommand

backend/src/main/kotlin/io/zell/zdb/log/LogContentReader.kt, backend/src/test/kotlin/ZeebeLogTest.java, cli/src/main/java/io/zell/zdb/LogPrintCommand.java
Moves filtering and the from and to specifications to the backend such that we can better write test for that logic, and the CLI code becomes more simplified.
Furthermore, improved the command options descriptions in the cli.
=> Move new log print logic to backend

backend/src/main/kotlin/io/zell/zdb/journal/file/EmptySegmentException.java, backend/src/main/kotlin/io/zell/zdb/journal/file/SegmentDescriptorReader.java, backend/src/main/kotlin/io/zell/zdb/journal/file/SegmentsManager.java, backend/src/test/kotlin/io/zell/zdb/ZeebeContentCreator.java, backend/src/test/kotlin/io/zell/zdb/latest/VersionLatestTest.java, backend/src/test/kotlin/io/zell/zdb/v81/Version81Test.java, backend/src/test/kotlin/io/zell/zdb/v82/Version82Test.java, backend/src/test/kotlin/io/zell/zdb/v83/Version83Test.java
Zeebe creates segments async, which are not yet initialized this causes zdb to fail because it expects certain meta data, we will ingore such from now on.
Added tests to reproduce this in different versions.
@deepthidevaki fyi
=> Ignore empty async created segments

backend/pom.xml, frontend/pom.xml, frontend/src/main/java/io/zell/zdb/frontend/LogViewController.java, frontend/src/main/java/io/zell/zdb/frontend/StateViewController.java, frontend/src/main/java/io/zell/zdb/frontend/TableViewKeyEventClipboardCopier.java, frontend/src/main/java/io/zell/zdb/frontend/ZdbApplication.java, frontend/src/main/java/io/zell/zdb/frontend/ZdbFrontendMain.java, frontend/src/main/java/io/zell/zdb/frontend/ZeebeRecord.java, frontend/src/main/resources/io/zell/zdb/frontend/log-view.fxml, frontend/src/main/resources/io/zell/zdb/frontend/state-view.fxml, frontend/src/main/resources/io/zell/zdb/frontend/zdb-view.fxml, pom.xml
Adds frontend (JavaFX based) to ZDB that allows to investigate the log, with similar feature as printing the log via zdb cli
Furthermore, it allows to investigate the state with all existing column families. It uses the key formatter functionally recently added to ZDB to correctly print the keys. All values are printed as JSON values.
=> Add Frontend to ZDB

cli/src/main/java/io/zell/zdb/state/StateCommand.java
To allow small column family names
```
./zdb state list -cf key -p raft-partition/partitions/1/snapshots/15-1-38-53/
{"data":[java.lang.IllegalArgumentException: No enum constant io.camunda.zeebe.protocol.ZbColumnFamilies.key
at java.base/java.lang.Enum.valueOf(Enum.java:293)
at io.camunda.zeebe.protocol.ZbColumnFamilies.valueOf(ZbColumnFamilies.java:18)
at io.zell.zdb.state.StateCommand.lambda$list$2(StateCommand.java:81)
at io.zell.zdb.JsonPrinter.surround(JsonPrinter.java:60)
at io.zell.zdb.state.StateCommand.list(StateCommand.java:65)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at picocli.CommandLine.executeUserObject(CommandLine.java:2070)
at …
```
=> Convert given CF names

backend/src/main/kotlin/io/zell/zdb/state/KeyFormatter.java
If an keyformatter is wrong previously zdb failed with IndexOutOfBounce exceptions. This commit allows to still print the key in hex format, to handle errors more gracefully
For example on printing the state it previously failed with:
```
{"cf":"PROCESS_CACHE_DIGEST_BY_ID","key":"<default>:Process_04inzbr","value":{"digest":"R6Fk39sgsbKmot1FTKZ3Cg=="}}java.lang.IndexOutOfBoundsException: index=41 length=524288 capacity=58
at org.agrona.AbstractMutableDirectBuffer.boundsCheck0(AbstractMutableDirectBuffer.java:1719)
at org.agrona.AbstractMutableDirectBuffer.getBytes(AbstractMutableDirectBuffer.java:450)
at io.camunda.zeebe.db.impl.DbString.wrap(DbString.java:37)
at io.zell.zdb.state.KeyFormatter$DbValueFormatter.formatKey(KeyFormatter.java:69)
at …
```
=> fix: err fallback on key formatting

backend/src/test/kotlin/io/zell/zdb/latest/VersionLatestTest.java
Latest test is almost always failing with 8.7-8.8, as lot of new records etc have introduced, and blocks CI But this has not much value, right now as we dont support it officially yet.
=> test: disable latest test

README.md
Banned instance command is no longer supported. I've replaced the old command documentation with the new alternative.
=> doc: update banned instance inspection document
